import { Canvas, useFrame } from '@react-three/fiber';
import { motion } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';

const stack = [
  { name: 'PHP', slug: 'php' }, { name: 'React', slug: 'react' },
  { name: 'Vue', slug: 'vuedotjs' }, { name: 'Laravel', slug: 'laravel' },
  { name: 'Express', slug: 'express' }, { name: 'MySQL', slug: 'mysql' },
  { name: 'JavaScript', slug: 'javascript' }, { name: 'Figma', slug: 'figma' },
];

function OrbitalSystem() {
  const group = useRef<THREE.Group>(null);
  useFrame((state) => { if (group.current) group.current.rotation.y = state.clock.elapsedTime * .16; });
  return <group ref={group} rotation={[.45, 0, .2]}>
    {[1.5, 1.98, 2.46].map((r, i) => <mesh key={r}><torusGeometry args={[r, .008, 8, 80]}/><meshBasicMaterial color="#11120f" transparent opacity={.22 + i * .08}/></mesh>)}
  </group>;
}
function ThreeBackdrop() { return <Canvas camera={{ position: [0, 0, 7.5], fov: 44 }} className="pointer-events-none absolute inset-0"><ambientLight intensity={.25}/><pointLight position={[2,2,3]} color="#c2ff4b" intensity={20}/><OrbitalSystem/></Canvas>; }
const Reveal = ({ children, className = '' }: { children: React.ReactNode; className?: string }) => <motion.div className={className} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: .55 }}>{children}</motion.div>;
const TechIcons = () => <div className="flex shrink-0 items-center">{stack.map((tech) => <span key={tech.slug} className="group relative mr-10 inline-flex h-20 w-14 items-center justify-center"><img src={`https://cdn.simpleicons.org/${tech.slug}/10110e`} alt={tech.name} className="h-10 w-10 transition-transform duration-200 group-hover:scale-110"/><span className="pointer-events-none absolute top-1 left-1/2 -translate-x-1/2 whitespace-nowrap bg-[#10110e] px-2 py-1 text-[10px] font-bold text-[#f2f1eb] opacity-0 transition-opacity duration-200 group-hover:opacity-100">{tech.name}</span><b className="absolute -right-5 text-sm">✦</b></span>)}</div>;

export function App() { return <div className="min-h-screen overflow-hidden bg-[#f2f1eb] font-sans text-[#10110e] selection:bg-[#c2ff4b]">
  <header className="relative flex h-19 items-center border-b border-black/10 px-6 md:px-[7vw]"><a href="#top" className="text-2xl font-black tracking-[-.15em]">RJB<span className="text-[#94c82a]">_</span></a><nav className="hidden gap-8 text-sm font-bold md:absolute md:left-1/2 md:-ml-8 md:-translate-x-1/2 md:flex"><a href="#experience">Experience</a><a href="#work">Projects</a><a href="#about">About</a><a href="#contact">Contact</a></nav></header>
  <main id="top"><section className="relative grid min-h-[640px] grid-cols-1 overflow-hidden border-b border-black/10 lg:grid-cols-[1.15fr_.85fr]"><div className="hero-orbit pointer-events-none absolute inset-0 z-0"><ThreeBackdrop/></div><div className="relative z-10 flex flex-col justify-center px-6 py-16 md:px-[10vw]"><p className="mb-8 font-mono text-[11px] tracking-[.12em] text-black/60"><span className="mr-3 inline-block h-2 w-2 rounded-full bg-[#a6de35] shadow-[0_0_0_6px_#c2ff4b55]"/>BSIT GRADUATE · AVAILABLE FOR OPPORTUNITIES</p><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="text-[clamp(3.9rem,6vw,6rem)] font-extrabold leading-[.86] tracking-[-.09em] lg:whitespace-nowrap">Code with<br/><em className="font-serif font-normal">character.</em></motion.h1><p className="mt-7 max-w-sm text-[15px] leading-7">I’m Reagan — a fresh BSIT graduate seeking full-stack development and IT support opportunities, with a focus on useful systems, streamlined digital workflows, and clear web experiences.</p><div className="mt-8 flex flex-wrap items-center gap-6"><a className="bg-[#c2ff4b] px-7 py-5 text-xs font-extrabold" href="#work">Explore projects　↓</a><a className="border-b border-black pb-1 text-xs font-bold" href="mailto:balansagreagan@gmail.com">Email me　↗</a></div></div>
    <div className="relative z-10 min-h-[500px] overflow-hidden bg-transparent"><motion.figure initial={{opacity:0,scale:.88,rotate:-9}} animate={{opacity:1,scale:1,rotate:-4}} transition={{duration:.8,delay:.2}} className="absolute left-1/2 top-1/2 z-10 h-[350px] w-[250px] -translate-x-1/2 -translate-y-1/2 border border-[#8ebf27] bg-white p-2 shadow-[18px_18px_0_#c2ff4b66] lg:top-[190px] lg:-translate-y-0"><img src="/profile.jpg" alt="Reagan Balansag in graduation attire" className="h-full w-full object-cover object-[center_15%]"/><figcaption className="absolute bottom-4 right-4 bg-white/90 px-2 py-1 font-mono text-[9px] text-[#527511]">RJB / 2026</figcaption></motion.figure><div className="pointer-events-none absolute bottom-7 left-7 z-20 font-mono text-[10px] leading-5 tracking-wider text-black/55">SYSTEM / ONLINE<br/><span className="text-[#527511]">PLARIDEL, PH</span></div></div></section>
  <div className="flex h-24 overflow-hidden bg-[#c2ff4b]"><div className="flex w-max animate-[marquee-loop_20s_linear_infinite] items-center hover:[animation-play-state:paused]"><TechIcons/><TechIcons/><TechIcons/><TechIcons/></div></div>
  <section id="about" className="bg-[#24251f] px-6 py-24 text-[#f2f1eb] md:px-[10vw] md:py-40"><Reveal><p className="mb-7 font-mono text-[10px] tracking-widest text-white/60">01 / A LITTLE ABOUT ME</p><h2 className="max-w-5xl text-[clamp(2.8rem,6vw,5.7rem)] font-bold leading-[.93] tracking-[-.07em]">I like the point where a <em className="font-serif font-normal">good idea</em> becomes a tool someone can actually use.</h2><div className="mt-14 grid gap-10 md:grid-cols-[170px_minmax(0,1fr)_120px] md:items-end"><figure className="relative w-36 rotate-[-4deg] border border-[#c2ff4b] bg-white p-1 shadow-[10px_10px_0_#c2ff4b44]"><img src="/profile.jpg" alt="Reagan Balansag" className="aspect-[3/4] w-full object-cover object-[center_15%]"/></figure><div><p className="max-w-xl text-sm leading-7 text-white/75">I am a Bachelor of Science in Information Technology graduate from Misamis University, eager to explore the IT industry through full-stack development, technical support, and practical digital solutions. I enjoy learning new tools, solving real operational problems, and contributing to teams that build technology people can rely on.</p><a href="/BalansagCV.pdf" download className="mt-7 inline-block border-b border-[#c2ff4b] pb-1 text-xs font-extrabold text-[#c2ff4b]">Download my CV ↓</a></div><a href="#contact" className="grid h-30 w-30 place-content-center rounded-full bg-[#c2ff4b] text-center text-xs font-extrabold text-black">Let’s work<br/>together ↘</a></div></Reveal></section>
  <section id="experience" className="bg-white px-6 py-24 md:px-[10vw] md:py-36"><Reveal><div className="mb-12 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-[10px] tracking-widest">02 / WORK EXPERIENCE</p><h2 className="mt-4 text-[clamp(2.6rem,5vw,4.8rem)] font-bold leading-[.9] tracking-[-.07em]">Practical work,<br/><em className="font-serif font-normal">real impact.</em></h2></div><p className="max-w-sm text-sm leading-6 text-black/60">Experience across web development, IT support, data management, and operational systems.</p></div><div className="border-t border-black"><ExperienceItem date="05/2026 — 08/2026" role="Web Developer & Social Media Manager" organization="SDFP — Sapang Dalaga Floating Playground" detail="Developed and maintained website experiences and automated digital workflows. Managed social content, promotions, and online customer engagement."/><ExperienceItem date="02/2026 — 05/2026" role="OJT — Enterprise HR Information System" organization="Department of Education, Division of Ozamiz City" detail="Developed and improved EHRIS modules with Laravel, Vue.js, and MySQL; performed debugging, system testing, database work, Git collaboration, and documentation."/><ExperienceItem date="05/2023 — 06/2023" role="Summer Job — Data Entry & IT Support" organization="PESO Office — Plaridel, Misamis Occidental" detail="Maintained accurate records, prepared documents, helped with computer setup and software installation, and resolved basic hardware and software issues."/></div></Reveal></section>
  <section id="work" className="px-6 py-24 md:px-[10vw] md:py-36"><Reveal><div className="mb-10 flex flex-col justify-between gap-4 md:flex-row md:items-end"><p className="font-mono text-[10px] tracking-widest">03 / PROJECTS</p><p className="text-xs text-black/55">Systems built for real people and everyday operations.</p></div></Reveal><div className="grid gap-5 md:grid-cols-2"><SmartOutletProject/><EhrisProject/><SdfpProject/></div></section>
  <section className="px-6 pb-24 md:px-[10vw]"><Reveal><p className="mb-7 font-mono text-[10px] tracking-widest">04 / WHAT I BRING</p><div className="border-t border-black">{[['01','Full-stack systems','PHP · Laravel · React · Vue.js'],['02','Data & integration','MySQL · PostgreSQL · MongoDB · APIs'],['03','Technical operations','Git · Docker · Networking · IT Support']].map(s=><div key={s[0]} className="grid grid-cols-[40px_1fr_20px] gap-3 border-b border-black py-7 md:grid-cols-[80px_1fr_1fr_25px]"><span className="font-mono text-[10px] text-black/55">{s[0]}</span><h3 className="text-xl font-bold tracking-tight">{s[1]}</h3><p className="col-start-2 font-mono text-[10px] text-black/55 md:col-auto">{s[2]}</p><b>↗</b></div>)}</div></Reveal></section>
  <section id="contact" className="bg-[#c2ff4b] px-6 py-24 md:px-[10vw] md:py-36"><Reveal><p className="mb-7 font-mono text-[10px] tracking-widest">05 / GET IN TOUCH</p><h2 className="text-[clamp(3rem,6vw,6rem)] font-bold leading-[.9] tracking-[-.07em]">Have a useful problem?<br/><em className="font-serif font-normal">Let’s make it real.</em></h2><a className="mt-14 inline-block border-b-2 border-black pb-2 text-xl font-bold md:text-3xl" href="mailto:balansagreagan@gmail.com">balansagreagan@gmail.com　↗</a><div className="mt-28 flex justify-between font-mono text-[10px] leading-5 text-black/65"><p>P-1 Danao, Plaridel<br/>Misamis Occidental, Philippines<br/>+63 930 312 0946</p><p>© {new Date().getFullYear()} Reagan Balansag<br/>Built with intent.</p></div></Reveal></section></main><PortfolioChatbot/></div>; }

type ChatMessage = { role: 'bot' | 'user'; text: string };
const starterQuestions = ['What are Reagan’s core skills?', 'Which projects has Reagan worked on?', 'What are Reagan’s interests outside work?', 'How can I get in touch with Reagan?'];

function getPortfolioReply(question: string) {
  const text = question.toLowerCase();
  if (/(hello|hi|hey)/.test(text)) return 'Hi! I’m Reagan’s portfolio assistant. Ask about his skills, work experience, projects, education, hobbies, or contact details.';
  if (/(contact|email|phone|reach|get in touch|hire)/.test(text)) return 'You can contact Reagan at balansagreagan@gmail.com or +63 930 312 0946. LinkedIn: linkedin.com/in/reagan-jade-balansag-5a20613ab.';
  if (/(hobby|hobbies|volleyball|mobile legend|explore|free time)/.test(text)) return 'Reagan enjoys creating responsive websites, playing volleyball and Mobile Legends, and exploring new ideas and technologies.';
  if (/(skill|technology|stack|programming|language)/.test(text)) return 'Reagan works with HTML, CSS, JavaScript, PHP, Laravel, React.js, Vue.js, MySQL, PostgreSQL, MongoDB, RESTful APIs, web and mobile development, database management, and technical support.';
  if (/(smart outlet|capstone|iot|energy|esp32|pzem)/.test(text)) return 'Reagan’s capstone is an IoT Smart Outlet Monitoring System for boarding houses. It uses ESP32, PZEM-004T, Vanilla PHP, MySQL, RESTful APIs, and Apache Cordova for real-time monitoring, remote outlet control, and automated billing.';
  if (/(ehris|hris|deped|ojt|intern)/.test(text)) return 'During his OJT with the Department of Education – Division of Ozamiz City, Reagan developed and enhanced EHRIS modules using Laravel, Vue.js, and MySQL. He worked on features, debugging, testing, database tasks, Git collaboration, and documentation.';
  if (/(sdfp|floating playground|social media|web developer|part time)/.test(text)) return 'As a part-time Web Developer and Social Media Manager for SDFP – Sapang Dalaga Floating Playground, Reagan maintained web experiences and digital workflows while handling content, promotions, and customer engagement.';
  if (/(peso|data entry|it support|experience|work)/.test(text)) return 'Reagan has hands-on experience in web development, IT support, data management, and operations. At the PESO Office, he handled data entry, document management, computer setup, software installation, troubleshooting, and confidential records.';
  if (/(education|graduate|school|university|degree)/.test(text)) return 'Reagan earned a Bachelor of Science in Information Technology from Misamis University (2022–2026). He completed Senior High School at Looc National High School.';
  if (/(certification|award|ccna|achievement)/.test(text)) return 'His certifications include Networking Devices and Initial Configuration, CCNA Switching, Routing, and Wireless Essentials, and CCNAv7 Introduction to Networks. He also received Best ICT Innovation for his capstone defense and was a Faculty’s Lister in AY 2023.';
  if (/(ya! pabili|delivery|merchant|rider|pasuyo)/.test(text)) return 'At Ya! Pabili, Reagan supported Admin/IT operations: rider and merchant accounts, orders, Pasuyo requests, merchant ads, system issues, and operational improvements.';
  if (/(project|portfolio|built)/.test(text)) return 'Reagan’s featured projects are the IoT Smart Outlet Monitoring System, the DepEd Enterprise HR Information System (EHRIS), and the Sapang Dalaga Floating Playground operations platform.';
  return 'I can help with Reagan’s skills, experience, projects, education, certifications, hobbies, or contact details. Try a suggested question below.';
}

function PortfolioChatbot() {
  const [open, setOpen] = useState(false);
  const [input, setInput] = useState('');
  const [isThinking, setIsThinking] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([{ role: 'bot', text: 'Hi! I’m Reagan’s portfolio assistant. What would you like to know?' }]);
  const newestMessageRef = useRef<HTMLDivElement>(null);
  useEffect(() => { newestMessageRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' }); }, [messages, isThinking]);
  const ask = (question: string) => {
    const value = question.trim();
    if (!value || isThinking) return;
    setMessages(current => [...current, { role: 'user', text: value }]);
    setInput('');
    setIsThinking(true);
    window.setTimeout(() => {
      setMessages(current => [...current, { role: 'bot', text: getPortfolioReply(value) }]);
      setIsThinking(false);
    }, 550);
  };
  return <aside className="portfolio-chat" aria-label="Portfolio assistant">
    {open && <div className="portfolio-chat__panel"><div className="portfolio-chat__header"><div><span className="portfolio-chat__status"/> ASK REAGAN</div><button onClick={() => setOpen(false)} aria-label="Close chat">×</button></div><div className="portfolio-chat__messages" aria-live="polite">{messages.map((message, index) => <motion.p key={index} initial={{ opacity: 0, y: 10, scale: .97 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .22, ease: 'easeOut' }} className={`portfolio-chat__message portfolio-chat__message--${message.role}`}>{message.text}</motion.p>)}{isThinking && <motion.p initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} className="portfolio-chat__typing"><i/><i/><i/></motion.p>}<div ref={newestMessageRef}/></div><div className="portfolio-chat__suggestions">{starterQuestions.map(question => <button key={question} onClick={() => ask(question)} disabled={isThinking}>{question}</button>)}</div><form className="portfolio-chat__form" onSubmit={event => { event.preventDefault(); ask(input); }}><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask about Reagan..." disabled={isThinking}/><button type="submit" aria-label="Send message" disabled={isThinking}>↑</button></form></div>}
    {!open && <button className="portfolio-chat__toggle" onClick={() => setOpen(true)} aria-expanded={false}>Ask Reagan <span>↗</span></button>}
  </aside>;
}

function ExperienceItem({ date, role, organization, detail }: { date: string; role: string; organization: string; detail: string }) {
  return <article className="grid gap-4 border-b border-black py-7 md:grid-cols-[150px_minmax(0,1fr)_minmax(0,1fr)] md:gap-8"><p className="font-mono text-[10px] leading-5 text-black/55">{date}</p><div><h3 className="text-xl font-bold tracking-tight">{role}</h3><p className="mt-2 font-mono text-[10px] leading-5 text-[#527511]">{organization}</p></div><p className="text-sm leading-6 text-black/65">{detail}</p></article>;
}
function SmartOutletProject(){return <Reveal><article><div className="relative h-80 overflow-hidden bg-white"><img src="/smartoutlet.png" alt="Smart Outlet Monitoring system preview" className="h-full w-full object-contain object-center"/><span className="absolute bottom-5 left-5 rounded-full bg-[#10110e] px-3 py-2 font-mono text-[10px] text-white">LOCAL PROJECT</span></div><p className="mt-6 font-mono text-[10px] text-black/55">01</p><h3 className="mt-3 text-3xl font-bold leading-[.95] tracking-[-.06em]">Smart Outlet<br/>Monitoring</h3><p className="mt-3 max-w-sm text-xs leading-6 text-black/60">An IoT energy-management system for boarding houses, providing real-time outlet monitoring, remote control, usage tracking, and automated billing through web and mobile interfaces.</p><div className="mt-5 flex gap-2"><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">VANILLA PHP</span><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">MYSQL</span><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">ESP32</span></div></article></Reveal>}
function EhrisProject(){return <Reveal><a href="http://58.69.118.16:85/ehris/" target="_blank" rel="noreferrer" className="group block"><div className="relative grid h-80 place-items-center overflow-hidden bg-[#e8edf4]"><img src="/ehris.png" alt="DepEd eHRIS logo" className="max-h-64 w-[88%] object-contain transition-transform duration-300 group-hover:scale-105"/><span className="absolute right-5 top-5 rounded-full bg-[#10110e] px-3 py-2 font-mono text-[10px] text-white">VIEW LIVE ↗</span></div><p className="mt-6 font-mono text-[10px] text-black/55">02</p><h3 className="mt-3 text-3xl font-bold leading-[.95] tracking-[-.06em]">Enterprise HR<br/>Information System</h3><p className="mt-3 max-w-sm text-xs leading-6 text-black/60">A centralized human resource information system for DepEd Ozamiz that streamlines personnel records, leave workflows, locator slips, and document tracking through a secure, role-based platform.</p><div className="mt-5 flex gap-2"><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">LARAVEL</span><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">VUE.JS</span><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">MYSQL</span></div></a></Reveal>}
function SdfpProject(){return <Reveal><a href="https://sdfp.yannabiz.online/" target="_blank" rel="noreferrer" className="group block"><div className="relative h-80 overflow-hidden bg-[#153a5d]"><img src="/sdfp.jpg" alt="Sapang Dalaga Floating Playground system preview" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 to-transparent"/><span className="absolute right-5 top-5 rounded-full bg-[#c2ff4b] px-3 py-2 font-mono text-[10px] font-bold text-black">VIEW LIVE ↗</span><p className="absolute bottom-5 left-5 font-mono text-[10px] tracking-widest text-white/80">SDFP / OPERATIONS PLATFORM</p></div><p className="mt-6 font-mono text-[10px] text-black/55">03</p><h3 className="mt-3 text-3xl font-bold leading-[.95] tracking-[-.06em]">Sapang Dalaga<br/>Floating Playground</h3><p className="mt-3 max-w-sm text-xs leading-6 text-black/60">A unified operations management platform that brings bookings, attendance, sales, inventory, payroll, staff records, and reporting into one reliable workflow for day-to-day business operations.</p><div className="mt-5 flex gap-2"><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">LARAVEL</span><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">REACT</span><span className="rounded-full border border-black/15 px-2 py-1 font-mono text-[9px]">MONGODB</span></div></a></Reveal>}
